const MimeTypes = new Map(Object.entries({
  bmp:     'image/bmp',
  css:     'text/css',
  csv:     'text/csv',
  eot:     'application/vnd.ms-fontobject',
  gif:     'image/gif',
  htm:     'text/html',
  html:    'text/html',
  ico:     'image/vnd.microsoft.icon',
  jpeg:    'image/jpeg',
  jpg:     'image/jpeg',
  js:      'text/javascript',
  json:    'application/json',
  jsonld:  'application/ld+json',
  jsonp:   'application/javascript',
  mjs:     'text/javascript',
  mp3:     'audio/mpeg',
  mp4:     'video/mp4',
  ogg:     'audio/ogg',
  otf:     'font/otf',
  pdf:     'application/pdf',
  png:     'image/png',
  rar:     'application/x-rar-compressed',
  svg:     'image/svg+xml',
  tar:     'application/x-tar',
  ttf:     'font/ttf',
  txt:     'text/plain',
  wav:     'audio/wav',
  webp:    'image/webp',
  woff2:   'font/woff2',
  xml:     'application/xml',
  zip:     'application/zip',
  woff:    'font/woff',
}))

export default MimeTypes
